name: Testtesttest
favicon: null
layout_spectrum: 0.9900991152971983
typography_spectrum: 0.6333305300213397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9605928210075945
  lightness: 0.5496847613248974
  saturation: 0.04185560345649719
  rhythmicContrast: 0.7943299289327115
purpose: []
